package com.wsxd.main.entity;

import java.util.ArrayList;
import java.util.List;

public class AssetLossExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table asset_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table asset_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table asset_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public AssetLossExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table asset_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDateMonthIsNull() {
            addCriterion("date_month is null");
            return (Criteria) this;
        }

        public Criteria andDateMonthIsNotNull() {
            addCriterion("date_month is not null");
            return (Criteria) this;
        }

        public Criteria andDateMonthEqualTo(String value) {
            addCriterion("date_month =", value, "dateMonth");
            return (Criteria) this;
        }

        public Criteria andDateMonthNotEqualTo(String value) {
            addCriterion("date_month <>", value, "dateMonth");
            return (Criteria) this;
        }

        public Criteria andDateMonthGreaterThan(String value) {
            addCriterion("date_month >", value, "dateMonth");
            return (Criteria) this;
        }

        public Criteria andDateMonthGreaterThanOrEqualTo(String value) {
            addCriterion("date_month >=", value, "dateMonth");
            return (Criteria) this;
        }

        public Criteria andDateMonthLessThan(String value) {
            addCriterion("date_month <", value, "dateMonth");
            return (Criteria) this;
        }

        public Criteria andDateMonthLessThanOrEqualTo(String value) {
            addCriterion("date_month <=", value, "dateMonth");
            return (Criteria) this;
        }

        public Criteria andDateMonthLike(String value) {
            addCriterion("date_month like", value, "dateMonth");
            return (Criteria) this;
        }

        public Criteria andDateMonthNotLike(String value) {
            addCriterion("date_month not like", value, "dateMonth");
            return (Criteria) this;
        }

        public Criteria andDateMonthIn(List<String> values) {
            addCriterion("date_month in", values, "dateMonth");
            return (Criteria) this;
        }

        public Criteria andDateMonthNotIn(List<String> values) {
            addCriterion("date_month not in", values, "dateMonth");
            return (Criteria) this;
        }

        public Criteria andDateMonthBetween(String value1, String value2) {
            addCriterion("date_month between", value1, value2, "dateMonth");
            return (Criteria) this;
        }

        public Criteria andDateMonthNotBetween(String value1, String value2) {
            addCriterion("date_month not between", value1, value2, "dateMonth");
            return (Criteria) this;
        }

        public Criteria andNormalBalanceIsNull() {
            addCriterion("normal_balance is null");
            return (Criteria) this;
        }

        public Criteria andNormalBalanceIsNotNull() {
            addCriterion("normal_balance is not null");
            return (Criteria) this;
        }

        public Criteria andNormalBalanceEqualTo(String value) {
            addCriterion("normal_balance =", value, "normalBalance");
            return (Criteria) this;
        }

        public Criteria andNormalBalanceNotEqualTo(String value) {
            addCriterion("normal_balance <>", value, "normalBalance");
            return (Criteria) this;
        }

        public Criteria andNormalBalanceGreaterThan(String value) {
            addCriterion("normal_balance >", value, "normalBalance");
            return (Criteria) this;
        }

        public Criteria andNormalBalanceGreaterThanOrEqualTo(String value) {
            addCriterion("normal_balance >=", value, "normalBalance");
            return (Criteria) this;
        }

        public Criteria andNormalBalanceLessThan(String value) {
            addCriterion("normal_balance <", value, "normalBalance");
            return (Criteria) this;
        }

        public Criteria andNormalBalanceLessThanOrEqualTo(String value) {
            addCriterion("normal_balance <=", value, "normalBalance");
            return (Criteria) this;
        }

        public Criteria andNormalBalanceLike(String value) {
            addCriterion("normal_balance like", value, "normalBalance");
            return (Criteria) this;
        }

        public Criteria andNormalBalanceNotLike(String value) {
            addCriterion("normal_balance not like", value, "normalBalance");
            return (Criteria) this;
        }

        public Criteria andNormalBalanceIn(List<String> values) {
            addCriterion("normal_balance in", values, "normalBalance");
            return (Criteria) this;
        }

        public Criteria andNormalBalanceNotIn(List<String> values) {
            addCriterion("normal_balance not in", values, "normalBalance");
            return (Criteria) this;
        }

        public Criteria andNormalBalanceBetween(String value1, String value2) {
            addCriterion("normal_balance between", value1, value2, "normalBalance");
            return (Criteria) this;
        }

        public Criteria andNormalBalanceNotBetween(String value1, String value2) {
            addCriterion("normal_balance not between", value1, value2, "normalBalance");
            return (Criteria) this;
        }

        public Criteria andNormalRateIsNull() {
            addCriterion("normal_rate is null");
            return (Criteria) this;
        }

        public Criteria andNormalRateIsNotNull() {
            addCriterion("normal_rate is not null");
            return (Criteria) this;
        }

        public Criteria andNormalRateEqualTo(String value) {
            addCriterion("normal_rate =", value, "normalRate");
            return (Criteria) this;
        }

        public Criteria andNormalRateNotEqualTo(String value) {
            addCriterion("normal_rate <>", value, "normalRate");
            return (Criteria) this;
        }

        public Criteria andNormalRateGreaterThan(String value) {
            addCriterion("normal_rate >", value, "normalRate");
            return (Criteria) this;
        }

        public Criteria andNormalRateGreaterThanOrEqualTo(String value) {
            addCriterion("normal_rate >=", value, "normalRate");
            return (Criteria) this;
        }

        public Criteria andNormalRateLessThan(String value) {
            addCriterion("normal_rate <", value, "normalRate");
            return (Criteria) this;
        }

        public Criteria andNormalRateLessThanOrEqualTo(String value) {
            addCriterion("normal_rate <=", value, "normalRate");
            return (Criteria) this;
        }

        public Criteria andNormalRateLike(String value) {
            addCriterion("normal_rate like", value, "normalRate");
            return (Criteria) this;
        }

        public Criteria andNormalRateNotLike(String value) {
            addCriterion("normal_rate not like", value, "normalRate");
            return (Criteria) this;
        }

        public Criteria andNormalRateIn(List<String> values) {
            addCriterion("normal_rate in", values, "normalRate");
            return (Criteria) this;
        }

        public Criteria andNormalRateNotIn(List<String> values) {
            addCriterion("normal_rate not in", values, "normalRate");
            return (Criteria) this;
        }

        public Criteria andNormalRateBetween(String value1, String value2) {
            addCriterion("normal_rate between", value1, value2, "normalRate");
            return (Criteria) this;
        }

        public Criteria andNormalRateNotBetween(String value1, String value2) {
            addCriterion("normal_rate not between", value1, value2, "normalRate");
            return (Criteria) this;
        }

        public Criteria andNormalRealIsNull() {
            addCriterion("normal_real is null");
            return (Criteria) this;
        }

        public Criteria andNormalRealIsNotNull() {
            addCriterion("normal_real is not null");
            return (Criteria) this;
        }

        public Criteria andNormalRealEqualTo(String value) {
            addCriterion("normal_real =", value, "normalReal");
            return (Criteria) this;
        }

        public Criteria andNormalRealNotEqualTo(String value) {
            addCriterion("normal_real <>", value, "normalReal");
            return (Criteria) this;
        }

        public Criteria andNormalRealGreaterThan(String value) {
            addCriterion("normal_real >", value, "normalReal");
            return (Criteria) this;
        }

        public Criteria andNormalRealGreaterThanOrEqualTo(String value) {
            addCriterion("normal_real >=", value, "normalReal");
            return (Criteria) this;
        }

        public Criteria andNormalRealLessThan(String value) {
            addCriterion("normal_real <", value, "normalReal");
            return (Criteria) this;
        }

        public Criteria andNormalRealLessThanOrEqualTo(String value) {
            addCriterion("normal_real <=", value, "normalReal");
            return (Criteria) this;
        }

        public Criteria andNormalRealLike(String value) {
            addCriterion("normal_real like", value, "normalReal");
            return (Criteria) this;
        }

        public Criteria andNormalRealNotLike(String value) {
            addCriterion("normal_real not like", value, "normalReal");
            return (Criteria) this;
        }

        public Criteria andNormalRealIn(List<String> values) {
            addCriterion("normal_real in", values, "normalReal");
            return (Criteria) this;
        }

        public Criteria andNormalRealNotIn(List<String> values) {
            addCriterion("normal_real not in", values, "normalReal");
            return (Criteria) this;
        }

        public Criteria andNormalRealBetween(String value1, String value2) {
            addCriterion("normal_real between", value1, value2, "normalReal");
            return (Criteria) this;
        }

        public Criteria andNormalRealNotBetween(String value1, String value2) {
            addCriterion("normal_real not between", value1, value2, "normalReal");
            return (Criteria) this;
        }

        public Criteria andFollowBalanceIsNull() {
            addCriterion("follow_balance is null");
            return (Criteria) this;
        }

        public Criteria andFollowBalanceIsNotNull() {
            addCriterion("follow_balance is not null");
            return (Criteria) this;
        }

        public Criteria andFollowBalanceEqualTo(String value) {
            addCriterion("follow_balance =", value, "followBalance");
            return (Criteria) this;
        }

        public Criteria andFollowBalanceNotEqualTo(String value) {
            addCriterion("follow_balance <>", value, "followBalance");
            return (Criteria) this;
        }

        public Criteria andFollowBalanceGreaterThan(String value) {
            addCriterion("follow_balance >", value, "followBalance");
            return (Criteria) this;
        }

        public Criteria andFollowBalanceGreaterThanOrEqualTo(String value) {
            addCriterion("follow_balance >=", value, "followBalance");
            return (Criteria) this;
        }

        public Criteria andFollowBalanceLessThan(String value) {
            addCriterion("follow_balance <", value, "followBalance");
            return (Criteria) this;
        }

        public Criteria andFollowBalanceLessThanOrEqualTo(String value) {
            addCriterion("follow_balance <=", value, "followBalance");
            return (Criteria) this;
        }

        public Criteria andFollowBalanceLike(String value) {
            addCriterion("follow_balance like", value, "followBalance");
            return (Criteria) this;
        }

        public Criteria andFollowBalanceNotLike(String value) {
            addCriterion("follow_balance not like", value, "followBalance");
            return (Criteria) this;
        }

        public Criteria andFollowBalanceIn(List<String> values) {
            addCriterion("follow_balance in", values, "followBalance");
            return (Criteria) this;
        }

        public Criteria andFollowBalanceNotIn(List<String> values) {
            addCriterion("follow_balance not in", values, "followBalance");
            return (Criteria) this;
        }

        public Criteria andFollowBalanceBetween(String value1, String value2) {
            addCriterion("follow_balance between", value1, value2, "followBalance");
            return (Criteria) this;
        }

        public Criteria andFollowBalanceNotBetween(String value1, String value2) {
            addCriterion("follow_balance not between", value1, value2, "followBalance");
            return (Criteria) this;
        }

        public Criteria andFollowRateIsNull() {
            addCriterion("follow_rate is null");
            return (Criteria) this;
        }

        public Criteria andFollowRateIsNotNull() {
            addCriterion("follow_rate is not null");
            return (Criteria) this;
        }

        public Criteria andFollowRateEqualTo(String value) {
            addCriterion("follow_rate =", value, "followRate");
            return (Criteria) this;
        }

        public Criteria andFollowRateNotEqualTo(String value) {
            addCriterion("follow_rate <>", value, "followRate");
            return (Criteria) this;
        }

        public Criteria andFollowRateGreaterThan(String value) {
            addCriterion("follow_rate >", value, "followRate");
            return (Criteria) this;
        }

        public Criteria andFollowRateGreaterThanOrEqualTo(String value) {
            addCriterion("follow_rate >=", value, "followRate");
            return (Criteria) this;
        }

        public Criteria andFollowRateLessThan(String value) {
            addCriterion("follow_rate <", value, "followRate");
            return (Criteria) this;
        }

        public Criteria andFollowRateLessThanOrEqualTo(String value) {
            addCriterion("follow_rate <=", value, "followRate");
            return (Criteria) this;
        }

        public Criteria andFollowRateLike(String value) {
            addCriterion("follow_rate like", value, "followRate");
            return (Criteria) this;
        }

        public Criteria andFollowRateNotLike(String value) {
            addCriterion("follow_rate not like", value, "followRate");
            return (Criteria) this;
        }

        public Criteria andFollowRateIn(List<String> values) {
            addCriterion("follow_rate in", values, "followRate");
            return (Criteria) this;
        }

        public Criteria andFollowRateNotIn(List<String> values) {
            addCriterion("follow_rate not in", values, "followRate");
            return (Criteria) this;
        }

        public Criteria andFollowRateBetween(String value1, String value2) {
            addCriterion("follow_rate between", value1, value2, "followRate");
            return (Criteria) this;
        }

        public Criteria andFollowRateNotBetween(String value1, String value2) {
            addCriterion("follow_rate not between", value1, value2, "followRate");
            return (Criteria) this;
        }

        public Criteria andFollowRealIsNull() {
            addCriterion("follow_real is null");
            return (Criteria) this;
        }

        public Criteria andFollowRealIsNotNull() {
            addCriterion("follow_real is not null");
            return (Criteria) this;
        }

        public Criteria andFollowRealEqualTo(String value) {
            addCriterion("follow_real =", value, "followReal");
            return (Criteria) this;
        }

        public Criteria andFollowRealNotEqualTo(String value) {
            addCriterion("follow_real <>", value, "followReal");
            return (Criteria) this;
        }

        public Criteria andFollowRealGreaterThan(String value) {
            addCriterion("follow_real >", value, "followReal");
            return (Criteria) this;
        }

        public Criteria andFollowRealGreaterThanOrEqualTo(String value) {
            addCriterion("follow_real >=", value, "followReal");
            return (Criteria) this;
        }

        public Criteria andFollowRealLessThan(String value) {
            addCriterion("follow_real <", value, "followReal");
            return (Criteria) this;
        }

        public Criteria andFollowRealLessThanOrEqualTo(String value) {
            addCriterion("follow_real <=", value, "followReal");
            return (Criteria) this;
        }

        public Criteria andFollowRealLike(String value) {
            addCriterion("follow_real like", value, "followReal");
            return (Criteria) this;
        }

        public Criteria andFollowRealNotLike(String value) {
            addCriterion("follow_real not like", value, "followReal");
            return (Criteria) this;
        }

        public Criteria andFollowRealIn(List<String> values) {
            addCriterion("follow_real in", values, "followReal");
            return (Criteria) this;
        }

        public Criteria andFollowRealNotIn(List<String> values) {
            addCriterion("follow_real not in", values, "followReal");
            return (Criteria) this;
        }

        public Criteria andFollowRealBetween(String value1, String value2) {
            addCriterion("follow_real between", value1, value2, "followReal");
            return (Criteria) this;
        }

        public Criteria andFollowRealNotBetween(String value1, String value2) {
            addCriterion("follow_real not between", value1, value2, "followReal");
            return (Criteria) this;
        }

        public Criteria andMinorBalanceIsNull() {
            addCriterion("minor_balance is null");
            return (Criteria) this;
        }

        public Criteria andMinorBalanceIsNotNull() {
            addCriterion("minor_balance is not null");
            return (Criteria) this;
        }

        public Criteria andMinorBalanceEqualTo(String value) {
            addCriterion("minor_balance =", value, "minorBalance");
            return (Criteria) this;
        }

        public Criteria andMinorBalanceNotEqualTo(String value) {
            addCriterion("minor_balance <>", value, "minorBalance");
            return (Criteria) this;
        }

        public Criteria andMinorBalanceGreaterThan(String value) {
            addCriterion("minor_balance >", value, "minorBalance");
            return (Criteria) this;
        }

        public Criteria andMinorBalanceGreaterThanOrEqualTo(String value) {
            addCriterion("minor_balance >=", value, "minorBalance");
            return (Criteria) this;
        }

        public Criteria andMinorBalanceLessThan(String value) {
            addCriterion("minor_balance <", value, "minorBalance");
            return (Criteria) this;
        }

        public Criteria andMinorBalanceLessThanOrEqualTo(String value) {
            addCriterion("minor_balance <=", value, "minorBalance");
            return (Criteria) this;
        }

        public Criteria andMinorBalanceLike(String value) {
            addCriterion("minor_balance like", value, "minorBalance");
            return (Criteria) this;
        }

        public Criteria andMinorBalanceNotLike(String value) {
            addCriterion("minor_balance not like", value, "minorBalance");
            return (Criteria) this;
        }

        public Criteria andMinorBalanceIn(List<String> values) {
            addCriterion("minor_balance in", values, "minorBalance");
            return (Criteria) this;
        }

        public Criteria andMinorBalanceNotIn(List<String> values) {
            addCriterion("minor_balance not in", values, "minorBalance");
            return (Criteria) this;
        }

        public Criteria andMinorBalanceBetween(String value1, String value2) {
            addCriterion("minor_balance between", value1, value2, "minorBalance");
            return (Criteria) this;
        }

        public Criteria andMinorBalanceNotBetween(String value1, String value2) {
            addCriterion("minor_balance not between", value1, value2, "minorBalance");
            return (Criteria) this;
        }

        public Criteria andMinorRateIsNull() {
            addCriterion("minor_rate is null");
            return (Criteria) this;
        }

        public Criteria andMinorRateIsNotNull() {
            addCriterion("minor_rate is not null");
            return (Criteria) this;
        }

        public Criteria andMinorRateEqualTo(String value) {
            addCriterion("minor_rate =", value, "minorRate");
            return (Criteria) this;
        }

        public Criteria andMinorRateNotEqualTo(String value) {
            addCriterion("minor_rate <>", value, "minorRate");
            return (Criteria) this;
        }

        public Criteria andMinorRateGreaterThan(String value) {
            addCriterion("minor_rate >", value, "minorRate");
            return (Criteria) this;
        }

        public Criteria andMinorRateGreaterThanOrEqualTo(String value) {
            addCriterion("minor_rate >=", value, "minorRate");
            return (Criteria) this;
        }

        public Criteria andMinorRateLessThan(String value) {
            addCriterion("minor_rate <", value, "minorRate");
            return (Criteria) this;
        }

        public Criteria andMinorRateLessThanOrEqualTo(String value) {
            addCriterion("minor_rate <=", value, "minorRate");
            return (Criteria) this;
        }

        public Criteria andMinorRateLike(String value) {
            addCriterion("minor_rate like", value, "minorRate");
            return (Criteria) this;
        }

        public Criteria andMinorRateNotLike(String value) {
            addCriterion("minor_rate not like", value, "minorRate");
            return (Criteria) this;
        }

        public Criteria andMinorRateIn(List<String> values) {
            addCriterion("minor_rate in", values, "minorRate");
            return (Criteria) this;
        }

        public Criteria andMinorRateNotIn(List<String> values) {
            addCriterion("minor_rate not in", values, "minorRate");
            return (Criteria) this;
        }

        public Criteria andMinorRateBetween(String value1, String value2) {
            addCriterion("minor_rate between", value1, value2, "minorRate");
            return (Criteria) this;
        }

        public Criteria andMinorRateNotBetween(String value1, String value2) {
            addCriterion("minor_rate not between", value1, value2, "minorRate");
            return (Criteria) this;
        }

        public Criteria andMinorRealIsNull() {
            addCriterion("minor_real is null");
            return (Criteria) this;
        }

        public Criteria andMinorRealIsNotNull() {
            addCriterion("minor_real is not null");
            return (Criteria) this;
        }

        public Criteria andMinorRealEqualTo(String value) {
            addCriterion("minor_real =", value, "minorReal");
            return (Criteria) this;
        }

        public Criteria andMinorRealNotEqualTo(String value) {
            addCriterion("minor_real <>", value, "minorReal");
            return (Criteria) this;
        }

        public Criteria andMinorRealGreaterThan(String value) {
            addCriterion("minor_real >", value, "minorReal");
            return (Criteria) this;
        }

        public Criteria andMinorRealGreaterThanOrEqualTo(String value) {
            addCriterion("minor_real >=", value, "minorReal");
            return (Criteria) this;
        }

        public Criteria andMinorRealLessThan(String value) {
            addCriterion("minor_real <", value, "minorReal");
            return (Criteria) this;
        }

        public Criteria andMinorRealLessThanOrEqualTo(String value) {
            addCriterion("minor_real <=", value, "minorReal");
            return (Criteria) this;
        }

        public Criteria andMinorRealLike(String value) {
            addCriterion("minor_real like", value, "minorReal");
            return (Criteria) this;
        }

        public Criteria andMinorRealNotLike(String value) {
            addCriterion("minor_real not like", value, "minorReal");
            return (Criteria) this;
        }

        public Criteria andMinorRealIn(List<String> values) {
            addCriterion("minor_real in", values, "minorReal");
            return (Criteria) this;
        }

        public Criteria andMinorRealNotIn(List<String> values) {
            addCriterion("minor_real not in", values, "minorReal");
            return (Criteria) this;
        }

        public Criteria andMinorRealBetween(String value1, String value2) {
            addCriterion("minor_real between", value1, value2, "minorReal");
            return (Criteria) this;
        }

        public Criteria andMinorRealNotBetween(String value1, String value2) {
            addCriterion("minor_real not between", value1, value2, "minorReal");
            return (Criteria) this;
        }

        public Criteria andSuspiciousBalanceIsNull() {
            addCriterion("suspicious_balance is null");
            return (Criteria) this;
        }

        public Criteria andSuspiciousBalanceIsNotNull() {
            addCriterion("suspicious_balance is not null");
            return (Criteria) this;
        }

        public Criteria andSuspiciousBalanceEqualTo(String value) {
            addCriterion("suspicious_balance =", value, "suspiciousBalance");
            return (Criteria) this;
        }

        public Criteria andSuspiciousBalanceNotEqualTo(String value) {
            addCriterion("suspicious_balance <>", value, "suspiciousBalance");
            return (Criteria) this;
        }

        public Criteria andSuspiciousBalanceGreaterThan(String value) {
            addCriterion("suspicious_balance >", value, "suspiciousBalance");
            return (Criteria) this;
        }

        public Criteria andSuspiciousBalanceGreaterThanOrEqualTo(String value) {
            addCriterion("suspicious_balance >=", value, "suspiciousBalance");
            return (Criteria) this;
        }

        public Criteria andSuspiciousBalanceLessThan(String value) {
            addCriterion("suspicious_balance <", value, "suspiciousBalance");
            return (Criteria) this;
        }

        public Criteria andSuspiciousBalanceLessThanOrEqualTo(String value) {
            addCriterion("suspicious_balance <=", value, "suspiciousBalance");
            return (Criteria) this;
        }

        public Criteria andSuspiciousBalanceLike(String value) {
            addCriterion("suspicious_balance like", value, "suspiciousBalance");
            return (Criteria) this;
        }

        public Criteria andSuspiciousBalanceNotLike(String value) {
            addCriterion("suspicious_balance not like", value, "suspiciousBalance");
            return (Criteria) this;
        }

        public Criteria andSuspiciousBalanceIn(List<String> values) {
            addCriterion("suspicious_balance in", values, "suspiciousBalance");
            return (Criteria) this;
        }

        public Criteria andSuspiciousBalanceNotIn(List<String> values) {
            addCriterion("suspicious_balance not in", values, "suspiciousBalance");
            return (Criteria) this;
        }

        public Criteria andSuspiciousBalanceBetween(String value1, String value2) {
            addCriterion("suspicious_balance between", value1, value2, "suspiciousBalance");
            return (Criteria) this;
        }

        public Criteria andSuspiciousBalanceNotBetween(String value1, String value2) {
            addCriterion("suspicious_balance not between", value1, value2, "suspiciousBalance");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRateIsNull() {
            addCriterion("suspicious_rate is null");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRateIsNotNull() {
            addCriterion("suspicious_rate is not null");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRateEqualTo(String value) {
            addCriterion("suspicious_rate =", value, "suspiciousRate");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRateNotEqualTo(String value) {
            addCriterion("suspicious_rate <>", value, "suspiciousRate");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRateGreaterThan(String value) {
            addCriterion("suspicious_rate >", value, "suspiciousRate");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRateGreaterThanOrEqualTo(String value) {
            addCriterion("suspicious_rate >=", value, "suspiciousRate");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRateLessThan(String value) {
            addCriterion("suspicious_rate <", value, "suspiciousRate");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRateLessThanOrEqualTo(String value) {
            addCriterion("suspicious_rate <=", value, "suspiciousRate");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRateLike(String value) {
            addCriterion("suspicious_rate like", value, "suspiciousRate");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRateNotLike(String value) {
            addCriterion("suspicious_rate not like", value, "suspiciousRate");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRateIn(List<String> values) {
            addCriterion("suspicious_rate in", values, "suspiciousRate");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRateNotIn(List<String> values) {
            addCriterion("suspicious_rate not in", values, "suspiciousRate");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRateBetween(String value1, String value2) {
            addCriterion("suspicious_rate between", value1, value2, "suspiciousRate");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRateNotBetween(String value1, String value2) {
            addCriterion("suspicious_rate not between", value1, value2, "suspiciousRate");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRealIsNull() {
            addCriterion("suspicious_real is null");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRealIsNotNull() {
            addCriterion("suspicious_real is not null");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRealEqualTo(String value) {
            addCriterion("suspicious_real =", value, "suspiciousReal");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRealNotEqualTo(String value) {
            addCriterion("suspicious_real <>", value, "suspiciousReal");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRealGreaterThan(String value) {
            addCriterion("suspicious_real >", value, "suspiciousReal");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRealGreaterThanOrEqualTo(String value) {
            addCriterion("suspicious_real >=", value, "suspiciousReal");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRealLessThan(String value) {
            addCriterion("suspicious_real <", value, "suspiciousReal");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRealLessThanOrEqualTo(String value) {
            addCriterion("suspicious_real <=", value, "suspiciousReal");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRealLike(String value) {
            addCriterion("suspicious_real like", value, "suspiciousReal");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRealNotLike(String value) {
            addCriterion("suspicious_real not like", value, "suspiciousReal");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRealIn(List<String> values) {
            addCriterion("suspicious_real in", values, "suspiciousReal");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRealNotIn(List<String> values) {
            addCriterion("suspicious_real not in", values, "suspiciousReal");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRealBetween(String value1, String value2) {
            addCriterion("suspicious_real between", value1, value2, "suspiciousReal");
            return (Criteria) this;
        }

        public Criteria andSuspiciousRealNotBetween(String value1, String value2) {
            addCriterion("suspicious_real not between", value1, value2, "suspiciousReal");
            return (Criteria) this;
        }

        public Criteria andLossBalanceIsNull() {
            addCriterion("loss_balance is null");
            return (Criteria) this;
        }

        public Criteria andLossBalanceIsNotNull() {
            addCriterion("loss_balance is not null");
            return (Criteria) this;
        }

        public Criteria andLossBalanceEqualTo(String value) {
            addCriterion("loss_balance =", value, "lossBalance");
            return (Criteria) this;
        }

        public Criteria andLossBalanceNotEqualTo(String value) {
            addCriterion("loss_balance <>", value, "lossBalance");
            return (Criteria) this;
        }

        public Criteria andLossBalanceGreaterThan(String value) {
            addCriterion("loss_balance >", value, "lossBalance");
            return (Criteria) this;
        }

        public Criteria andLossBalanceGreaterThanOrEqualTo(String value) {
            addCriterion("loss_balance >=", value, "lossBalance");
            return (Criteria) this;
        }

        public Criteria andLossBalanceLessThan(String value) {
            addCriterion("loss_balance <", value, "lossBalance");
            return (Criteria) this;
        }

        public Criteria andLossBalanceLessThanOrEqualTo(String value) {
            addCriterion("loss_balance <=", value, "lossBalance");
            return (Criteria) this;
        }

        public Criteria andLossBalanceLike(String value) {
            addCriterion("loss_balance like", value, "lossBalance");
            return (Criteria) this;
        }

        public Criteria andLossBalanceNotLike(String value) {
            addCriterion("loss_balance not like", value, "lossBalance");
            return (Criteria) this;
        }

        public Criteria andLossBalanceIn(List<String> values) {
            addCriterion("loss_balance in", values, "lossBalance");
            return (Criteria) this;
        }

        public Criteria andLossBalanceNotIn(List<String> values) {
            addCriterion("loss_balance not in", values, "lossBalance");
            return (Criteria) this;
        }

        public Criteria andLossBalanceBetween(String value1, String value2) {
            addCriterion("loss_balance between", value1, value2, "lossBalance");
            return (Criteria) this;
        }

        public Criteria andLossBalanceNotBetween(String value1, String value2) {
            addCriterion("loss_balance not between", value1, value2, "lossBalance");
            return (Criteria) this;
        }

        public Criteria andLossRateIsNull() {
            addCriterion("loss_rate is null");
            return (Criteria) this;
        }

        public Criteria andLossRateIsNotNull() {
            addCriterion("loss_rate is not null");
            return (Criteria) this;
        }

        public Criteria andLossRateEqualTo(String value) {
            addCriterion("loss_rate =", value, "lossRate");
            return (Criteria) this;
        }

        public Criteria andLossRateNotEqualTo(String value) {
            addCriterion("loss_rate <>", value, "lossRate");
            return (Criteria) this;
        }

        public Criteria andLossRateGreaterThan(String value) {
            addCriterion("loss_rate >", value, "lossRate");
            return (Criteria) this;
        }

        public Criteria andLossRateGreaterThanOrEqualTo(String value) {
            addCriterion("loss_rate >=", value, "lossRate");
            return (Criteria) this;
        }

        public Criteria andLossRateLessThan(String value) {
            addCriterion("loss_rate <", value, "lossRate");
            return (Criteria) this;
        }

        public Criteria andLossRateLessThanOrEqualTo(String value) {
            addCriterion("loss_rate <=", value, "lossRate");
            return (Criteria) this;
        }

        public Criteria andLossRateLike(String value) {
            addCriterion("loss_rate like", value, "lossRate");
            return (Criteria) this;
        }

        public Criteria andLossRateNotLike(String value) {
            addCriterion("loss_rate not like", value, "lossRate");
            return (Criteria) this;
        }

        public Criteria andLossRateIn(List<String> values) {
            addCriterion("loss_rate in", values, "lossRate");
            return (Criteria) this;
        }

        public Criteria andLossRateNotIn(List<String> values) {
            addCriterion("loss_rate not in", values, "lossRate");
            return (Criteria) this;
        }

        public Criteria andLossRateBetween(String value1, String value2) {
            addCriterion("loss_rate between", value1, value2, "lossRate");
            return (Criteria) this;
        }

        public Criteria andLossRateNotBetween(String value1, String value2) {
            addCriterion("loss_rate not between", value1, value2, "lossRate");
            return (Criteria) this;
        }

        public Criteria andLossRealIsNull() {
            addCriterion("loss_real is null");
            return (Criteria) this;
        }

        public Criteria andLossRealIsNotNull() {
            addCriterion("loss_real is not null");
            return (Criteria) this;
        }

        public Criteria andLossRealEqualTo(String value) {
            addCriterion("loss_real =", value, "lossReal");
            return (Criteria) this;
        }

        public Criteria andLossRealNotEqualTo(String value) {
            addCriterion("loss_real <>", value, "lossReal");
            return (Criteria) this;
        }

        public Criteria andLossRealGreaterThan(String value) {
            addCriterion("loss_real >", value, "lossReal");
            return (Criteria) this;
        }

        public Criteria andLossRealGreaterThanOrEqualTo(String value) {
            addCriterion("loss_real >=", value, "lossReal");
            return (Criteria) this;
        }

        public Criteria andLossRealLessThan(String value) {
            addCriterion("loss_real <", value, "lossReal");
            return (Criteria) this;
        }

        public Criteria andLossRealLessThanOrEqualTo(String value) {
            addCriterion("loss_real <=", value, "lossReal");
            return (Criteria) this;
        }

        public Criteria andLossRealLike(String value) {
            addCriterion("loss_real like", value, "lossReal");
            return (Criteria) this;
        }

        public Criteria andLossRealNotLike(String value) {
            addCriterion("loss_real not like", value, "lossReal");
            return (Criteria) this;
        }

        public Criteria andLossRealIn(List<String> values) {
            addCriterion("loss_real in", values, "lossReal");
            return (Criteria) this;
        }

        public Criteria andLossRealNotIn(List<String> values) {
            addCriterion("loss_real not in", values, "lossReal");
            return (Criteria) this;
        }

        public Criteria andLossRealBetween(String value1, String value2) {
            addCriterion("loss_real between", value1, value2, "lossReal");
            return (Criteria) this;
        }

        public Criteria andLossRealNotBetween(String value1, String value2) {
            addCriterion("loss_real not between", value1, value2, "lossReal");
            return (Criteria) this;
        }

        public Criteria andFlagIsNull() {
            addCriterion("flag is null");
            return (Criteria) this;
        }

        public Criteria andFlagIsNotNull() {
            addCriterion("flag is not null");
            return (Criteria) this;
        }

        public Criteria andFlagEqualTo(Integer value) {
            addCriterion("flag =", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotEqualTo(Integer value) {
            addCriterion("flag <>", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThan(Integer value) {
            addCriterion("flag >", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("flag >=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThan(Integer value) {
            addCriterion("flag <", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThanOrEqualTo(Integer value) {
            addCriterion("flag <=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagIn(List<Integer> values) {
            addCriterion("flag in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotIn(List<Integer> values) {
            addCriterion("flag not in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagBetween(Integer value1, Integer value2) {
            addCriterion("flag between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("flag not between", value1, value2, "flag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table asset_loss
     *
     * @mbg.generated do_not_delete_during_merge Wed Jun 06 20:44:37 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table asset_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}