package com.wsxd.main.entity;

public class AssetLoss extends BaseReqBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_loss.date_month
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String dateMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_loss.normal_balance
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String normalBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_loss.normal_rate
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String normalRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_loss.normal_real
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String normalReal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_loss.follow_balance
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String followBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_loss.follow_rate
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String followRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_loss.follow_real
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String followReal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_loss.minor_balance
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String minorBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_loss.minor_rate
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String minorRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_loss.minor_real
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String minorReal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_loss.suspicious_balance
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String suspiciousBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_loss.suspicious_rate
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String suspiciousRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_loss.suspicious_real
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String suspiciousReal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_loss.loss_balance
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String lossBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_loss.loss_rate
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String lossRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_loss.loss_real
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String lossReal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_loss.flag
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_loss.date_month
     *
     * @return the value of asset_loss.date_month
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getDateMonth() {
        return dateMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_loss.date_month
     *
     * @param dateMonth the value for asset_loss.date_month
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setDateMonth(String dateMonth) {
        this.dateMonth = dateMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_loss.normal_balance
     *
     * @return the value of asset_loss.normal_balance
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getNormalBalance() {
        return normalBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_loss.normal_balance
     *
     * @param normalBalance the value for asset_loss.normal_balance
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setNormalBalance(String normalBalance) {
        this.normalBalance = normalBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_loss.normal_rate
     *
     * @return the value of asset_loss.normal_rate
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getNormalRate() {
        return normalRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_loss.normal_rate
     *
     * @param normalRate the value for asset_loss.normal_rate
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setNormalRate(String normalRate) {
        this.normalRate = normalRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_loss.normal_real
     *
     * @return the value of asset_loss.normal_real
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getNormalReal() {
        return normalReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_loss.normal_real
     *
     * @param normalReal the value for asset_loss.normal_real
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setNormalReal(String normalReal) {
        this.normalReal = normalReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_loss.follow_balance
     *
     * @return the value of asset_loss.follow_balance
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getFollowBalance() {
        return followBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_loss.follow_balance
     *
     * @param followBalance the value for asset_loss.follow_balance
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setFollowBalance(String followBalance) {
        this.followBalance = followBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_loss.follow_rate
     *
     * @return the value of asset_loss.follow_rate
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getFollowRate() {
        return followRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_loss.follow_rate
     *
     * @param followRate the value for asset_loss.follow_rate
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setFollowRate(String followRate) {
        this.followRate = followRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_loss.follow_real
     *
     * @return the value of asset_loss.follow_real
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getFollowReal() {
        return followReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_loss.follow_real
     *
     * @param followReal the value for asset_loss.follow_real
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setFollowReal(String followReal) {
        this.followReal = followReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_loss.minor_balance
     *
     * @return the value of asset_loss.minor_balance
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getMinorBalance() {
        return minorBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_loss.minor_balance
     *
     * @param minorBalance the value for asset_loss.minor_balance
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setMinorBalance(String minorBalance) {
        this.minorBalance = minorBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_loss.minor_rate
     *
     * @return the value of asset_loss.minor_rate
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getMinorRate() {
        return minorRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_loss.minor_rate
     *
     * @param minorRate the value for asset_loss.minor_rate
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setMinorRate(String minorRate) {
        this.minorRate = minorRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_loss.minor_real
     *
     * @return the value of asset_loss.minor_real
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getMinorReal() {
        return minorReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_loss.minor_real
     *
     * @param minorReal the value for asset_loss.minor_real
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setMinorReal(String minorReal) {
        this.minorReal = minorReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_loss.suspicious_balance
     *
     * @return the value of asset_loss.suspicious_balance
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getSuspiciousBalance() {
        return suspiciousBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_loss.suspicious_balance
     *
     * @param suspiciousBalance the value for asset_loss.suspicious_balance
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setSuspiciousBalance(String suspiciousBalance) {
        this.suspiciousBalance = suspiciousBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_loss.suspicious_rate
     *
     * @return the value of asset_loss.suspicious_rate
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getSuspiciousRate() {
        return suspiciousRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_loss.suspicious_rate
     *
     * @param suspiciousRate the value for asset_loss.suspicious_rate
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setSuspiciousRate(String suspiciousRate) {
        this.suspiciousRate = suspiciousRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_loss.suspicious_real
     *
     * @return the value of asset_loss.suspicious_real
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getSuspiciousReal() {
        return suspiciousReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_loss.suspicious_real
     *
     * @param suspiciousReal the value for asset_loss.suspicious_real
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setSuspiciousReal(String suspiciousReal) {
        this.suspiciousReal = suspiciousReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_loss.loss_balance
     *
     * @return the value of asset_loss.loss_balance
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getLossBalance() {
        return lossBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_loss.loss_balance
     *
     * @param lossBalance the value for asset_loss.loss_balance
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setLossBalance(String lossBalance) {
        this.lossBalance = lossBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_loss.loss_rate
     *
     * @return the value of asset_loss.loss_rate
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getLossRate() {
        return lossRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_loss.loss_rate
     *
     * @param lossRate the value for asset_loss.loss_rate
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setLossRate(String lossRate) {
        this.lossRate = lossRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_loss.loss_real
     *
     * @return the value of asset_loss.loss_real
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getLossReal() {
        return lossReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_loss.loss_real
     *
     * @param lossReal the value for asset_loss.loss_real
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setLossReal(String lossReal) {
        this.lossReal = lossReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_loss.flag
     *
     * @return the value of asset_loss.flag
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_loss.flag
     *
     * @param flag the value for asset_loss.flag
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}