package com.wsxd.main.entity;

public class ContractLoss extends BaseReqBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_loss.contract_number
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String contractNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_loss.bad_money
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String badMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_loss.loss_date
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String lossDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_loss.bad_type
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String badType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_loss.follow_up
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String followUp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_loss.flag
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_loss.contract_number
     *
     * @return the value of contract_loss.contract_number
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getContractNumber() {
        return contractNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_loss.contract_number
     *
     * @param contractNumber the value for contract_loss.contract_number
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setContractNumber(String contractNumber) {
        this.contractNumber = contractNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_loss.bad_money
     *
     * @return the value of contract_loss.bad_money
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getBadMoney() {
        return badMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_loss.bad_money
     *
     * @param badMoney the value for contract_loss.bad_money
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setBadMoney(String badMoney) {
        this.badMoney = badMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_loss.loss_date
     *
     * @return the value of contract_loss.loss_date
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getLossDate() {
        return lossDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_loss.loss_date
     *
     * @param lossDate the value for contract_loss.loss_date
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setLossDate(String lossDate) {
        this.lossDate = lossDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_loss.bad_type
     *
     * @return the value of contract_loss.bad_type
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getBadType() {
        return badType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_loss.bad_type
     *
     * @param badType the value for contract_loss.bad_type
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setBadType(String badType) {
        this.badType = badType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_loss.follow_up
     *
     * @return the value of contract_loss.follow_up
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getFollowUp() {
        return followUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_loss.follow_up
     *
     * @param followUp the value for contract_loss.follow_up
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setFollowUp(String followUp) {
        this.followUp = followUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_loss.flag
     *
     * @return the value of contract_loss.flag
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_loss.flag
     *
     * @param flag the value for contract_loss.flag
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}