package com.wsxd.main.entity;

public class DayReport extends BaseReqBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_report.check_date
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String checkDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_report.day_count
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String dayCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_report.day_money
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String dayMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_report.day_loan
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String dayLoan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_report.day_repay
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String dayRepay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_report.loan_balance
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String loanBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_report.loan_money
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String loanMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_report.loan_count
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String loanCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_report.flag
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_report.check_date
     *
     * @return the value of day_report.check_date
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getCheckDate() {
        return checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_report.check_date
     *
     * @param checkDate the value for day_report.check_date
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setCheckDate(String checkDate) {
        this.checkDate = checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_report.day_count
     *
     * @return the value of day_report.day_count
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getDayCount() {
        return dayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_report.day_count
     *
     * @param dayCount the value for day_report.day_count
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setDayCount(String dayCount) {
        this.dayCount = dayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_report.day_money
     *
     * @return the value of day_report.day_money
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getDayMoney() {
        return dayMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_report.day_money
     *
     * @param dayMoney the value for day_report.day_money
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setDayMoney(String dayMoney) {
        this.dayMoney = dayMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_report.day_loan
     *
     * @return the value of day_report.day_loan
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getDayLoan() {
        return dayLoan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_report.day_loan
     *
     * @param dayLoan the value for day_report.day_loan
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setDayLoan(String dayLoan) {
        this.dayLoan = dayLoan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_report.day_repay
     *
     * @return the value of day_report.day_repay
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getDayRepay() {
        return dayRepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_report.day_repay
     *
     * @param dayRepay the value for day_report.day_repay
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setDayRepay(String dayRepay) {
        this.dayRepay = dayRepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_report.loan_balance
     *
     * @return the value of day_report.loan_balance
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getLoanBalance() {
        return loanBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_report.loan_balance
     *
     * @param loanBalance the value for day_report.loan_balance
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setLoanBalance(String loanBalance) {
        this.loanBalance = loanBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_report.loan_money
     *
     * @return the value of day_report.loan_money
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getLoanMoney() {
        return loanMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_report.loan_money
     *
     * @param loanMoney the value for day_report.loan_money
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setLoanMoney(String loanMoney) {
        this.loanMoney = loanMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_report.loan_count
     *
     * @return the value of day_report.loan_count
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getLoanCount() {
        return loanCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_report.loan_count
     *
     * @param loanCount the value for day_report.loan_count
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setLoanCount(String loanCount) {
        this.loanCount = loanCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_report.flag
     *
     * @return the value of day_report.flag
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_report.flag
     *
     * @param flag the value for day_report.flag
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}