package com.wsxd.main.entity;

import java.util.List;

public class LoanContract extends BaseReqBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.contract_number
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String contractNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.contract_name
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String contractName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.borrower_type
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String borrowerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.money
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.term_type
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String termType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.term
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String term;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.start_date
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.end_date
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.rate_type
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String rateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.rate
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.annual_rate
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String annualRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.platform_cost
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String platformCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.is_entrust
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String isEntrust;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.purpose
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String purpose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.business
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String business;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.loan_method
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String loanMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.repay_method
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String repayMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.sign_time
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String signTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.repay_source
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String repaySource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.district_code
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String districtCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.flag
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private Integer flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.name
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.sex
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.card_type
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String cardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.card_number
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String cardNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.phone
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.is_farmer
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String isFarmer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.education
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.email
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.is_marry
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String isMarry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.nationality
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String nationality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.birthday
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.nation
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.address
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.post_code
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String postCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.registered_address
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String registeredAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.native_place
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String nativePlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.work_unit
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String workUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_contract.position
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String position;
    
    private PersonBorrower personBorrower;
    private List<RepayPlan> repayPlans;

    public PersonBorrower getPersonBorrower() {
		return personBorrower;
	}

	public void setPersonBorrower(PersonBorrower personBorrower) {
		this.personBorrower = personBorrower;
	}

	public List<RepayPlan> getRepayPlans() {
		return repayPlans;
	}

	public void setRepayPlans(List<RepayPlan> repayPlans) {
		this.repayPlans = repayPlans;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.contract_number
     *
     * @return the value of loan_contract.contract_number
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getContractNumber() {
        return contractNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.contract_number
     *
     * @param contractNumber the value for loan_contract.contract_number
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setContractNumber(String contractNumber) {
        this.contractNumber = contractNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.contract_name
     *
     * @return the value of loan_contract.contract_name
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getContractName() {
        return contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.contract_name
     *
     * @param contractName the value for loan_contract.contract_name
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setContractName(String contractName) {
        this.contractName = contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.borrower_type
     *
     * @return the value of loan_contract.borrower_type
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getBorrowerType() {
        return borrowerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.borrower_type
     *
     * @param borrowerType the value for loan_contract.borrower_type
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setBorrowerType(String borrowerType) {
        this.borrowerType = borrowerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.money
     *
     * @return the value of loan_contract.money
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.money
     *
     * @param money the value for loan_contract.money
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setMoney(String money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.term_type
     *
     * @return the value of loan_contract.term_type
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getTermType() {
        return termType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.term_type
     *
     * @param termType the value for loan_contract.term_type
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setTermType(String termType) {
        this.termType = termType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.term
     *
     * @return the value of loan_contract.term
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getTerm() {
        return term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.term
     *
     * @param term the value for loan_contract.term
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setTerm(String term) {
        this.term = term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.start_date
     *
     * @return the value of loan_contract.start_date
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.start_date
     *
     * @param startDate the value for loan_contract.start_date
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.end_date
     *
     * @return the value of loan_contract.end_date
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.end_date
     *
     * @param endDate the value for loan_contract.end_date
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.rate_type
     *
     * @return the value of loan_contract.rate_type
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getRateType() {
        return rateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.rate_type
     *
     * @param rateType the value for loan_contract.rate_type
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setRateType(String rateType) {
        this.rateType = rateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.rate
     *
     * @return the value of loan_contract.rate
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.rate
     *
     * @param rate the value for loan_contract.rate
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setRate(String rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.annual_rate
     *
     * @return the value of loan_contract.annual_rate
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getAnnualRate() {
        return annualRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.annual_rate
     *
     * @param annualRate the value for loan_contract.annual_rate
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setAnnualRate(String annualRate) {
        this.annualRate = annualRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.platform_cost
     *
     * @return the value of loan_contract.platform_cost
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getPlatformCost() {
        return platformCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.platform_cost
     *
     * @param platformCost the value for loan_contract.platform_cost
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setPlatformCost(String platformCost) {
        this.platformCost = platformCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.is_entrust
     *
     * @return the value of loan_contract.is_entrust
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getIsEntrust() {
        return isEntrust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.is_entrust
     *
     * @param isEntrust the value for loan_contract.is_entrust
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setIsEntrust(String isEntrust) {
        this.isEntrust = isEntrust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.purpose
     *
     * @return the value of loan_contract.purpose
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.purpose
     *
     * @param purpose the value for loan_contract.purpose
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setPurpose(String purpose) {
        this.purpose = purpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.business
     *
     * @return the value of loan_contract.business
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getBusiness() {
        return business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.business
     *
     * @param business the value for loan_contract.business
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setBusiness(String business) {
        this.business = business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.loan_method
     *
     * @return the value of loan_contract.loan_method
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getLoanMethod() {
        return loanMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.loan_method
     *
     * @param loanMethod the value for loan_contract.loan_method
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setLoanMethod(String loanMethod) {
        this.loanMethod = loanMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.repay_method
     *
     * @return the value of loan_contract.repay_method
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getRepayMethod() {
        return repayMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.repay_method
     *
     * @param repayMethod the value for loan_contract.repay_method
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setRepayMethod(String repayMethod) {
        this.repayMethod = repayMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.sign_time
     *
     * @return the value of loan_contract.sign_time
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getSignTime() {
        return signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.sign_time
     *
     * @param signTime the value for loan_contract.sign_time
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setSignTime(String signTime) {
        this.signTime = signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.repay_source
     *
     * @return the value of loan_contract.repay_source
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getRepaySource() {
        return repaySource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.repay_source
     *
     * @param repaySource the value for loan_contract.repay_source
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setRepaySource(String repaySource) {
        this.repaySource = repaySource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.district_code
     *
     * @return the value of loan_contract.district_code
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getDistrictCode() {
        return districtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.district_code
     *
     * @param districtCode the value for loan_contract.district_code
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.flag
     *
     * @return the value of loan_contract.flag
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.flag
     *
     * @param flag the value for loan_contract.flag
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.name
     *
     * @return the value of loan_contract.name
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.name
     *
     * @param name the value for loan_contract.name
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.sex
     *
     * @return the value of loan_contract.sex
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.sex
     *
     * @param sex the value for loan_contract.sex
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.card_type
     *
     * @return the value of loan_contract.card_type
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.card_type
     *
     * @param cardType the value for loan_contract.card_type
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setCardType(String cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.card_number
     *
     * @return the value of loan_contract.card_number
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.card_number
     *
     * @param cardNumber the value for loan_contract.card_number
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.phone
     *
     * @return the value of loan_contract.phone
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.phone
     *
     * @param phone the value for loan_contract.phone
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.is_farmer
     *
     * @return the value of loan_contract.is_farmer
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getIsFarmer() {
        return isFarmer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.is_farmer
     *
     * @param isFarmer the value for loan_contract.is_farmer
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setIsFarmer(String isFarmer) {
        this.isFarmer = isFarmer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.education
     *
     * @return the value of loan_contract.education
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.education
     *
     * @param education the value for loan_contract.education
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setEducation(String education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.email
     *
     * @return the value of loan_contract.email
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.email
     *
     * @param email the value for loan_contract.email
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.is_marry
     *
     * @return the value of loan_contract.is_marry
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getIsMarry() {
        return isMarry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.is_marry
     *
     * @param isMarry the value for loan_contract.is_marry
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setIsMarry(String isMarry) {
        this.isMarry = isMarry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.nationality
     *
     * @return the value of loan_contract.nationality
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.nationality
     *
     * @param nationality the value for loan_contract.nationality
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.birthday
     *
     * @return the value of loan_contract.birthday
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.birthday
     *
     * @param birthday the value for loan_contract.birthday
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.nation
     *
     * @return the value of loan_contract.nation
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.nation
     *
     * @param nation the value for loan_contract.nation
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setNation(String nation) {
        this.nation = nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.address
     *
     * @return the value of loan_contract.address
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.address
     *
     * @param address the value for loan_contract.address
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.post_code
     *
     * @return the value of loan_contract.post_code
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.post_code
     *
     * @param postCode the value for loan_contract.post_code
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.registered_address
     *
     * @return the value of loan_contract.registered_address
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getRegisteredAddress() {
        return registeredAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.registered_address
     *
     * @param registeredAddress the value for loan_contract.registered_address
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setRegisteredAddress(String registeredAddress) {
        this.registeredAddress = registeredAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.native_place
     *
     * @return the value of loan_contract.native_place
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getNativePlace() {
        return nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.native_place
     *
     * @param nativePlace the value for loan_contract.native_place
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.work_unit
     *
     * @return the value of loan_contract.work_unit
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getWorkUnit() {
        return workUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.work_unit
     *
     * @param workUnit the value for loan_contract.work_unit
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setWorkUnit(String workUnit) {
        this.workUnit = workUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_contract.position
     *
     * @return the value of loan_contract.position
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_contract.position
     *
     * @param position the value for loan_contract.position
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setPosition(String position) {
        this.position = position;
    }
}