package com.wsxd.main.entity;

public class LoanInfo extends BaseReqBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.id
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.contract_number
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String contractNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.money
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.loan_time
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String loanTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.start_date
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.end_date
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private String endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loan_info.flag
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.id
     *
     * @return the value of loan_info.id
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.id
     *
     * @param id the value for loan_info.id
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.contract_number
     *
     * @return the value of loan_info.contract_number
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getContractNumber() {
        return contractNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.contract_number
     *
     * @param contractNumber the value for loan_info.contract_number
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setContractNumber(String contractNumber) {
        this.contractNumber = contractNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.money
     *
     * @return the value of loan_info.money
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.money
     *
     * @param money the value for loan_info.money
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setMoney(String money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.loan_time
     *
     * @return the value of loan_info.loan_time
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getLoanTime() {
        return loanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.loan_time
     *
     * @param loanTime the value for loan_info.loan_time
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setLoanTime(String loanTime) {
        this.loanTime = loanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.start_date
     *
     * @return the value of loan_info.start_date
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.start_date
     *
     * @param startDate the value for loan_info.start_date
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.end_date
     *
     * @return the value of loan_info.end_date
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.end_date
     *
     * @param endDate the value for loan_info.end_date
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loan_info.flag
     *
     * @return the value of loan_info.flag
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loan_info.flag
     *
     * @param flag the value for loan_info.flag
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}