package com.wsxd.main.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;

public class RepayPlan extends BaseReqBean {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repay_plan.id
	 * @mbg.generated  Thu Jun 07 11:12:19 CST 2018
	 */
	@JsonIgnore 
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repay_plan.contract_number
	 * @mbg.generated  Thu Jun 07 11:12:19 CST 2018
	 */
	private String contractNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repay_plan.end_date
	 * @mbg.generated  Thu Jun 07 11:12:19 CST 2018
	 */
	private String endDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repay_plan.money
	 * @mbg.generated  Thu Jun 07 11:12:19 CST 2018
	 */
	private String money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repay_plan.interest
	 * @mbg.generated  Thu Jun 07 11:12:19 CST 2018
	 */
	private String interest;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repay_plan.extend_count
	 * @mbg.generated  Thu Jun 07 11:12:19 CST 2018
	 */
	private Integer extendCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repay_plan.flag
	 * @mbg.generated  Thu Jun 07 11:12:19 CST 2018
	 */
	@JsonIgnore 
	private Integer flag;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repay_plan.id
	 * @return  the value of repay_plan.id
	 * @mbg.generated  Thu Jun 07 11:12:19 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repay_plan.id
	 * @param id  the value for repay_plan.id
	 * @mbg.generated  Thu Jun 07 11:12:19 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repay_plan.contract_number
	 * @return  the value of repay_plan.contract_number
	 * @mbg.generated  Thu Jun 07 11:12:19 CST 2018
	 */
	public String getContractNumber() {
		return contractNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repay_plan.contract_number
	 * @param contractNumber  the value for repay_plan.contract_number
	 * @mbg.generated  Thu Jun 07 11:12:19 CST 2018
	 */
	public void setContractNumber(String contractNumber) {
		this.contractNumber = contractNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repay_plan.end_date
	 * @return  the value of repay_plan.end_date
	 * @mbg.generated  Thu Jun 07 11:12:19 CST 2018
	 */
	public String getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repay_plan.end_date
	 * @param endDate  the value for repay_plan.end_date
	 * @mbg.generated  Thu Jun 07 11:12:19 CST 2018
	 */
	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repay_plan.money
	 * @return  the value of repay_plan.money
	 * @mbg.generated  Thu Jun 07 11:12:19 CST 2018
	 */
	public String getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repay_plan.money
	 * @param money  the value for repay_plan.money
	 * @mbg.generated  Thu Jun 07 11:12:19 CST 2018
	 */
	public void setMoney(String money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repay_plan.interest
	 * @return  the value of repay_plan.interest
	 * @mbg.generated  Thu Jun 07 11:12:19 CST 2018
	 */
	public String getInterest() {
		return interest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repay_plan.interest
	 * @param interest  the value for repay_plan.interest
	 * @mbg.generated  Thu Jun 07 11:12:19 CST 2018
	 */
	public void setInterest(String interest) {
		this.interest = interest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repay_plan.extend_count
	 * @return  the value of repay_plan.extend_count
	 * @mbg.generated  Thu Jun 07 11:12:19 CST 2018
	 */
	public Integer getExtendCount() {
		return extendCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repay_plan.extend_count
	 * @param extendCount  the value for repay_plan.extend_count
	 * @mbg.generated  Thu Jun 07 11:12:19 CST 2018
	 */
	public void setExtendCount(Integer extendCount) {
		this.extendCount = extendCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repay_plan.flag
	 * @return  the value of repay_plan.flag
	 * @mbg.generated  Thu Jun 07 11:12:19 CST 2018
	 */
	public Integer getFlag() {
		return flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repay_plan.flag
	 * @param flag  the value for repay_plan.flag
	 * @mbg.generated  Thu Jun 07 11:12:19 CST 2018
	 */
	public void setFlag(Integer flag) {
		this.flag = flag;
	}

}