package com.wsxd.main.entity;

public class RepayInfo extends BaseReqBean {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repay_info.id
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repay_info.contract_number
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	private String contractNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repay_info.repay_time
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	private String repayTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repay_info.money
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	private String money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repay_info.interest
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	private String interest;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repay_info.penalty_interest
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	private String penaltyInterest;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repay_info.penalty
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	private String penalty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repay_info.service_charge
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	private String serviceCharge;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repay_info.other_charge
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	private String otherCharge;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repay_info.extend_flag
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	private Integer extendFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column repay_info.flag
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	private Integer flag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repay_info.id
	 * @return  the value of repay_info.id
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repay_info.id
	 * @param id  the value for repay_info.id
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repay_info.contract_number
	 * @return  the value of repay_info.contract_number
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	public String getContractNumber() {
		return contractNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repay_info.contract_number
	 * @param contractNumber  the value for repay_info.contract_number
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	public void setContractNumber(String contractNumber) {
		this.contractNumber = contractNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repay_info.repay_time
	 * @return  the value of repay_info.repay_time
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	public String getRepayTime() {
		return repayTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repay_info.repay_time
	 * @param repayTime  the value for repay_info.repay_time
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	public void setRepayTime(String repayTime) {
		this.repayTime = repayTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repay_info.money
	 * @return  the value of repay_info.money
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	public String getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repay_info.money
	 * @param money  the value for repay_info.money
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	public void setMoney(String money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repay_info.interest
	 * @return  the value of repay_info.interest
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	public String getInterest() {
		return interest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repay_info.interest
	 * @param interest  the value for repay_info.interest
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	public void setInterest(String interest) {
		this.interest = interest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repay_info.penalty_interest
	 * @return  the value of repay_info.penalty_interest
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	public String getPenaltyInterest() {
		return penaltyInterest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repay_info.penalty_interest
	 * @param penaltyInterest  the value for repay_info.penalty_interest
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	public void setPenaltyInterest(String penaltyInterest) {
		this.penaltyInterest = penaltyInterest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repay_info.penalty
	 * @return  the value of repay_info.penalty
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	public String getPenalty() {
		return penalty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repay_info.penalty
	 * @param penalty  the value for repay_info.penalty
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	public void setPenalty(String penalty) {
		this.penalty = penalty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repay_info.service_charge
	 * @return  the value of repay_info.service_charge
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	public String getServiceCharge() {
		return serviceCharge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repay_info.service_charge
	 * @param serviceCharge  the value for repay_info.service_charge
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	public void setServiceCharge(String serviceCharge) {
		this.serviceCharge = serviceCharge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repay_info.other_charge
	 * @return  the value of repay_info.other_charge
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	public String getOtherCharge() {
		return otherCharge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repay_info.other_charge
	 * @param otherCharge  the value for repay_info.other_charge
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	public void setOtherCharge(String otherCharge) {
		this.otherCharge = otherCharge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repay_info.extend_flag
	 * @return  the value of repay_info.extend_flag
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	public Integer getExtendFlag() {
		return extendFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repay_info.extend_flag
	 * @param extendFlag  the value for repay_info.extend_flag
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	public void setExtendFlag(Integer extendFlag) {
		this.extendFlag = extendFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column repay_info.flag
	 * @return  the value of repay_info.flag
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	public Integer getFlag() {
		return flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column repay_info.flag
	 * @param flag  the value for repay_info.flag
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	public void setFlag(Integer flag) {
		this.flag = flag;
	}
}