package com.wsxd.main.dao;

import com.wsxd.main.entity.AssetLoss;
import com.wsxd.main.entity.AssetLossExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AssetLossMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    long countByExample(AssetLossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    int deleteByExample(AssetLossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    int insert(AssetLoss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    int insertSelective(AssetLoss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    List<AssetLoss> selectByExample(AssetLossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") AssetLoss record, @Param("example") AssetLossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    int updateByExample(@Param("record") AssetLoss record, @Param("example") AssetLossExample example);
}