package com.wsxd.main.dao;

import com.wsxd.main.entity.ContractLoss;
import com.wsxd.main.entity.ContractLossExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContractLossMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    long countByExample(ContractLossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    int deleteByExample(ContractLossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    int insert(ContractLoss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    int insertSelective(ContractLoss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    List<ContractLoss> selectByExample(ContractLossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") ContractLoss record, @Param("example") ContractLossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_loss
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    int updateByExample(@Param("record") ContractLoss record, @Param("example") ContractLossExample example);
    
    /**
     * 逻辑删除坏账
     * @param record
     */
    void deleteContractLoss(String ContractNumber);
}