package com.wsxd.main.dao;

import com.wsxd.main.entity.DayReport;
import com.wsxd.main.entity.DayReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DayReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_report
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    long countByExample(DayReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_report
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    int deleteByExample(DayReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_report
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    int insert(DayReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_report
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    int insertSelective(DayReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_report
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    List<DayReport> selectByExample(DayReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_report
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") DayReport record, @Param("example") DayReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_report
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    int updateByExample(@Param("record") DayReport record, @Param("example") DayReportExample example);
}