package com.wsxd.main.dao;

import com.wsxd.main.entity.LoanInfo;
import com.wsxd.main.entity.LoanInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoanInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_info
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    long countByExample(LoanInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_info
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    int deleteByExample(LoanInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_info
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_info
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    int insert(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_info
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    int insertSelective(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_info
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    List<LoanInfo> selectByExample(LoanInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_info
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    LoanInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_info
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") LoanInfo record, @Param("example") LoanInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_info
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    int updateByExample(@Param("record") LoanInfo record, @Param("example") LoanInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_info
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    int updateByPrimaryKeySelective(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_info
     *
     * @mbg.generated Wed Jun 06 20:44:37 CST 2018
     */
    int updateByPrimaryKey(LoanInfo record);
}