package com.wsxd.main.dao;

import com.wsxd.main.entity.RepayPlan;
import com.wsxd.main.entity.RepayPlanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RepayPlanMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repay_plan
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	long countByExample(RepayPlanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repay_plan
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	int deleteByExample(RepayPlanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repay_plan
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repay_plan
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	int insert(RepayPlan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repay_plan
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	int insertSelective(RepayPlan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repay_plan
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */List<RepayPlan> selectByExample(RepayPlanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repay_plan
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	RepayPlan selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repay_plan
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */int updateByExampleSelective(@Param("record") RepayPlan record,@Param("example") RepayPlanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repay_plan
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */int updateByExample(@Param("record") RepayPlan record,@Param("example") RepayPlanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repay_plan
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	int updateByPrimaryKeySelective(RepayPlan record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repay_plan
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	int updateByPrimaryKey(RepayPlan record);
}