package com.wsxd.main.dao;

import com.wsxd.main.entity.RepayInfo;
import com.wsxd.main.entity.RepayInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RepayInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repay_info
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	long countByExample(RepayInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repay_info
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	int deleteByExample(RepayInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repay_info
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repay_info
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	int insert(RepayInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repay_info
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	int insertSelective(RepayInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repay_info
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */List<RepayInfo> selectByExample(RepayInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repay_info
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	RepayInfo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repay_info
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */int updateByExampleSelective(@Param("record") RepayInfo record,@Param("example") RepayInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repay_info
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */int updateByExample(@Param("record") RepayInfo record,@Param("example") RepayInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repay_info
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	int updateByPrimaryKeySelective(RepayInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table repay_info
	 * @mbg.generated  Wed Jun 06 21:49:40 CST 2018
	 */
	int updateByPrimaryKey(RepayInfo record);
}